[project]
name = "finetuneradiology-48838148"
version = "0.1.0"
description = "Pytorch based fine-tuning for radiology reports to layman summaries."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absl-py>=2.3.1",
    "accelerate>=1.11.0",
    "datasets>=4.2.0",
    "evaluate>=0.4.6",
    "hf-transfer>=0.1.9",
    "huggingface-hub>=0.35.3",
    "nltk>=3.9.2",
    "peft>=0.17.1",
    "python-dotenv>=1.1.1",
    "rouge-score>=0.1.2",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
